# Generated by Django 3.1.1 on 2020-09-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'vanilla'), ('COFFEE_FLAVOR_CARAMEL', 'caramel'), ('COFFEE_FLAVOR_PSL', 'psl'), ('COFFEE_FLAVOR_MOCHA', 'mocha'), ('COFFEE_FLAVOR_HAZELNUT', 'hazelnut')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.CharField(choices=[('DOZEN_1', '1 dozen'), ('DOZEN_3', '3 dozen'), ('DOZEN_5', '5 dozen'), ('DOZEN_7', '7 dozen')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_POD_LARGE', 'large coffee pod'), ('COFFEE_POD_SMALL', 'small coffee pod'), ('ESPRESSO_POD', 'espresso pod')], max_length=255)),
                ('coffee_flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.flavor')),
                ('pack_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.packsize')),
                ('sku_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku', to='core.machinecode')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'large machine'), ('COFFEE_MACHINE_SMALL', 'small machine'), ('ESPRESSO_MACHINE', 'espresso machine')], max_length=255)),
                ('water_line_compatible', models.BooleanField(default=False)),
                ('pod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pod', to='core.coffeepod')),
                ('sku_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code', to='core.coffeepod')),
            ],
        ),
    ]
