# Generated by Django 3.0.5 on 2020-09-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200916_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeemachine',
            name='model',
            field=models.CharField(choices=[('BASE', 'base model'), ('PREMIUM', 'premium model'), ('DELUXE', 'deluxe model')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
